### ISSUE TITLE
求联系方式

### ISSUE THREAD

**Issue by LordonCN** [TowerPro/nvidia-smi-helper#1]
同学你好，我在yolo3d那部分看到你的留言了，方便留个联系方式交流一下吗？微信、qq、邮箱均可，我最近也在用yolox+yolo3d进行自动驾驶单目视觉任务开发。

我的邮箱 xunjtech@gmail.com

**Comment by LordonCN** [comment]
其实我是想说apollo9.0已经上了yolo3d的代码..效果还是可以的

**Comment by TowerPro** [comment]
> 其实我是想说apollo9.0已经上了yolo3d的代码..效果还是可以的

好的，这是我的毕业设计，只能重新搓轮子
